import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#224875",
        "primary-container": "#48277a",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed": "#00201d",
        "surface-variant": "#d3e4fe",
        secondary: "#426560",
        "tertiary-container": "#113b67",
        "secondary-fixed-dim": "#a9cec7",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#486b66",
        "primary-fixed": "#ecdcff",
        "secondary-container": "#c4eae3",
        "tertiary-fixed-dim": "#a5c9fd",
        "secondary-fixed": "#c4eae3",
        "surface-container": "#e5eeff",
        "on-surface-variant": "#4a4550",
        "inverse-primary": "#d6baff",
        background: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "error-container": "#ffdad6",
        "surface-tint": "#6e4da1",
        outline: "#7b7481",
        "on-tertiary-container": "#83a6d8",
        "on-tertiary-fixed": "#001c39",
        "on-primary-fixed": "#270057",
        "outline-variant": "#ccc3d2",
        surface: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        error: "#ba1a1a",
        "on-primary-container": "#b693ed",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#d6baff",
        "on-primary-fixed-variant": "#553588",
        primary: "#310b63",
        "on-primary": "#ffffff",
        "on-surface": "#0b1c30",
        "on-background": "#0b1c30",
        tertiary: "#002548",
        "on-secondary-fixed-variant": "#2a4d48",
        "tertiary-fixed": "#d4e3ff",
        "inverse-surface": "#213145",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        xs: "4px",
        xl: "32px",
        gutter: "16px",
        md: "16px",
        lg: "24px",
        "container-margin": "20px",
        xxl: "48px",
        base: "8px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        h3: ["Plus Jakarta Sans", "sans-serif"],
        h1: ["Plus Jakarta Sans", "sans-serif"],
        h2: ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        h1: ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      boxShadow: {
        soft: "0 18px 50px -24px rgba(49, 11, 99, 0.24)",
        lift: "0 28px 70px -30px rgba(15, 23, 42, 0.35)",
      },
    },
  },
  plugins: [forms],
};
